<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="new1.aspx.cs" Inherits="Web1.new1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="StyleSheet1.css" rel="stylesheet" />
    <style type="text/css">
        h1{
            color:crimson;
            font-family:Arial;
        }
        #hh{color:blue;}
        .c1{
            color:chartreuse;

        }
        h1,h2{
            font-size:40px;
        }
        h3,p{
            font-size:x-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
         <%--   <h1 style="color:blueviolet;font-size:30px;">Hai All</h1>--%>
            <h1>HELLO....</h1>
            <h1>Welcome</h1>
            <h2>Good Morning</h2>
            <h1 id="hh">Liya Lesly</h1>
            <p>New in Bootstrap 5, our utilities are now generated by our Utility API. We built it as a feature-packed Sass map that can be quickly and easily customized. It's never been easier to add, remove, or modify any utility classes. Make utilities responsive, add pseudo-class variants, and give them custom names.</p>
            <p class="c1">fjfhfjghjghfgjkhfgjhfjgfhjhgjfhgj
                fngfgfgnfgnfgbnfbgnbgngbn
            </p>
            <h3 class="c1">hhhhhh</h3>
            <h3>ooooooo</h3>
        </div>
    </form>
</body>
</html>
